name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # Клонируем репозиторий
      - uses: actions/checkout@v3

        # Step's name
      - name: Use Node.js ${{ matrix.node-version }}
        # Устанавливаем Node.js
        - uses: actions/setup-node@v3
        # The Node.js version to configure
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: make setup
      - run: make start
      - run: make test
      - run: make lint
